services:
  postgres:
    image: postgres:16
    container_name: payments_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_int:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MOCK_URL: ${MOCK_URL_DOCKER}
      SECRET_KEY: ${SECRET_KEY}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: ["node", "src/app.js"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_worker
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    command: ["node", "src/out_box_worker.js"]

  mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_mock
    depends_on:
      app:
        condition: service_started
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${MOCK_PORT}
      APP_URL: ${APP_URL_DOCKER}
    ports:
      - "${MOCK_PORT}:${MOCK_PORT}"
    command: ["node", "public/mock-getaway-service/mock-app.js"]

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_tester
    depends_on:
      app:
        condition: service_started
      mock:
        condition: service_started
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PRODUCT_ID: ${PRODUCT_ID}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_PASSWORD: ${TEST_PASSWORD}
      APP_URL: ${APP_URL_DOCKER}
      MOCK_URL: ${MOCK_URL_DOCKER}
    command: ["node", "--test", "public/tests"]
    profiles: ["test"]

  get-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_get_metrics
    depends_on:
      app:
        condition: service_started
      mock:
        condition: service_started
    environment:
      SECRET_KEY: ${SECRET_KEY}
      APP_URL: ${APP_URL_DOCKER}
      MOCK_URL: ${MOCK_URL_DOCKER}
      RUNS: ${RUNS}
      PRODUCT_ID: ${PRODUCT_ID}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_PASSWORD: ${TEST_PASSWORD}
    command: ["node", "public/get_metrics.js"]
    profiles: ["metrics"]

volumes:
  postgres_data: